export const INDIAN_STATES = {
  "AP": "Andhra Pradesh",
  "AR": "Arunachal Pradesh",
  "AS": "Assam",
  "BR": "Bihar",
  "CT": "Chhattisgarh",
  "DL": "Delhi",
  "GA": "Goa",
  "GJ": "Gujarat",
  "HR": "Haryana",
  "HP": "Himachal Pradesh",
  "JK": "Jammu and Kashmir",
  "JH": "Jharkhand",
  "KA": "Karnataka",
  "KL": "Kerala",
  "MP": "Madhya Pradesh",
  "MH": "Maharashtra",
  "MN": "Manipur",
  "ML": "Meghalaya",
  "MZ": "Mizoram",
  "NL": "Nagaland",
  "OR": "Odisha",
  "PB": "Punjab",
  "RJ": "Rajasthan",
  "SK": "Sikkim",
  "TN": "Tamil Nadu",
  "TR": "Tripura",
  "UT": "Uttarakhand",
  "UP": "Uttar Pradesh",
  "WB": "West Bengal"
  };
  
  export const INCIDENT_CATEGORIES = [
    "fraud",
    "scam",
    "server",
    "money",
    "hacked",
    "laundering",
    "sextortion",
    "threats",
    "database",
    "data breach",
    "scrapping",
    "ddos",
    "steal",
    "phishing"
  ];
